#!/bin/bash
# HTTP ve HTTPS çıkışını engel kaldır
iptables -D OUTPUT -p tcp --dport 80 -j DROP
iptables -D OUTPUT -p tcp --dport 443 -j DROP
# HTTP ve HTTPS çıkışını engel kaldır
ip6tables -D OUTPUT -p tcp --dport 80 -j DROP
ip6tables -D OUTPUT -p tcp --dport 443 -j DROP
# HTTP ve HTTPS çıkışını engel kaldır
iptables -D OUTPUT -p udp --dport 80 -j DROP
iptables -D OUTPUT -p udp --dport 443 -j DROP
# HTTP ve HTTPS çıkışını engel kaldır
ip6tables -D OUTPUT -p udp --dport 80 -j DROP
ip6tables -D OUTPUT -p udp --dport 443 -j DROP
