#!/bin/bash

# 1) X11 reattach
MASTER=$(xinput list | grep "Virtual core keyboard" | grep -o "id=[0-9]*" | cut -d= -f2)
xinput reattach "$MASTER" "$MASTER" 2>/dev/null

# 2) libinput restore
for dev in /dev/input/event*; do
    chmod 660 "$dev"
    chown root:input "$dev"
done

# 3) Udev enable
for dev in /sys/class/input/event*/device/; do
    echo 1 > ${dev}../enabled 2>/dev/null
done

